#!/usr/bin/env bash
if [ "$2" = "" ]; then # if 2 arguments were not given
    echo "  dircompr: compare direct children of a two directories (recursive)"
    printf "  Usage:\tdircomp <path> <path>\n"
    exit 1
else # if 2 arguments were given
    if [ -d $1 ]; then # if the first argument is a directory
        if [ -d $2 ]; then # if the second argument is a directory
            DIRECTORIESA=0 # initializing a variable for the number of dirs in the first argument
            FILESA=0 # initializing a variable for the number of files in the first argument
            DIRECTORIESB=0 # initializing a variable for the number of dirs in the second argument
            FILESB=0 # initializing a variable for the number of files in the second argument
            searchdir () { # searchdir <0|1> <path> -- 0 for A, 1 for B, search the dir
                while read -r file; do # loop over all files in the first directory, with each file as "file"
                    if [ -f "$2/$file" ]; then # if it is a file
                        if [ $1 -eq 0 ]; then
                            ((FILESA++)) # increment the file counter
                        else
                            ((FILESB++)) # increment the file counter
                        fi
                    elif [ -d "$2/$file" ]; then # if it is a directory
                        if [ $1 -eq "0" ]; then
                            ((DIRECTORIESA++)) # increment the directory counter
                            searchdir 0 "$2/$file"
                        else # if it is neither a file nor a directory
                            ((DIRECTORIESB++)) # increment the directory counter
                            searchdir 1 "$2/$file"
                        fi
                    fi
                done < <(ls -1 $2 2> /dev/null) # pipe all filenames in the directory into the loop
            }
            searchdir 1 "$1" # search the first dir
            searchdir 0 "$2" # search the second dir
            if [ $FILESA -lt $FILESB ]; then # if there are less files in the first dir than the second dir
                echo "  $1 has more files than $2"
            elif [ $FILESA -eq $FILESB ]; then # if there are the same amount of files in the first dir than the second dir
                echo "  $1 has the same number of files as $2"
            else
                echo "  $2 has more files than $1"
            fi
            if [ $DIRECTORIESA -lt $DIRECTORIESB ]; then # if there are less dirs in the first dir than the second dir
                echo "  $1 has more directories than $2"
            elif [ $DIRECTORIESA -eq $DIRECTORIESB ]; then # if there are the same amount of dirs in the first dir than the second dir
                echo "  $1 has the same number of directories as $2"
            else # if there are more dirs in the second dir
                echo "  $2 has more directories than $1"
            fi
        else # if the second argument is not a dir
            printf "Fatal: $2 does not exist or it is not a directory"
            exit 1;
        fi
    else # if the first argument is not a dir
        printf "Fatal: $1 does not exist or it is not a directory"
        exit 1;
    fi
fi
