#!/usr/bin/env bash
if [ "$2" = "" ]; then # if 2 arguments were not given
    echo "  dircomp: compare direct children of a two directories"
    printf "  Usage:\tdircomp <path> <path>\n"
    exit 1
else
    if [ -d $1 ]; then # if the first argument is a directory
        if [ -d $2 ]; then # if the second argument is a directory
            DIRECTORIESA=0 # initiate a variable for the number of dirs in the first dir
            FILESA=0 # initiate a variable for the number of files in the first dir
            DIRECTORIESB=0 # initiate a variable for the number of dirs in the second dir
            FILESB=0 # initiate a variable for the number of files in the second dir
            while read -r file; do # loop over all files in the first directory, with each file as "file"
                if [ -f "$1/$file" ]; then # if it is a file
                    ((FILESA++)) # increment the file counter
                elif [ -d "$1/$file" ]; then # if it is a directory
                    ((DIRECTORIESA++)) # increment the directory counter
                fi
            done < <(ls -1 $1 2> /dev/null) # pipe all filenames in the directory into the loop
            while read -r file; do # loop over all files in the first directory, with each file as "file"
                if [ -f "$2/$file" ]; then # if it is a file
                    ((FILESB++)) # increment the file counter
                elif [ -d "$2/$file" ]; then # if it is a directory
                    ((DIRECTORIESB++)) # increment the directory counter
                fi
            done < <(ls -1 $2 2> /dev/null) # pipe all filenames in the directory into the loop
            if [ $FILESA -lt $FILESB ]; then # if there are less files in the first dir than the second dir
                echo "  $1 has more files than $2"
            elif [ $FILESA -eq $FILESB ]; then # if there are the same amount of files in the first dir than the second dir
                echo "  $1 has the same number of files as $2"
            else
                echo "  $2 has more files than $1"
            fi
            if [ $DIRECTORIESA -lt $DIRECTORIESB ]; then # if there are less dirs in the first dir than the second dir
                echo "  $1 has more directories than $2"
            elif [ $DIRECTORIESA -eq $DIRECTORIESB ]; then # if there are the same amount of dirs in the first dir than the second dir
                echo "  $1 has the same number of directories as $2"
            else
                echo "  $2 has more directories than $1"
            fi
        else # if the second argument is not a directory
            echo "Fatal: $2 does not exist or it is not a directory"
            exit 1
        fi
    else # if the first argument is not a directory
        echo "Fatal: $1 does not exist or it is not a directory"
        exit 1
    fi
fi
