#!/usr/bin/env bash
if [ "$1" = "" ]; then # if no argument is given
    echo "  fodr: test if a filename is a directory or a file or other (recursive)"
    printf "  Usage:\tfod <path>\n"
    exit 1
fi
echo "$1" | grep "^\/*\(\.\|\.\.\)\/*\(\/\+\.\|\/\+\.\.\)*\/*$" # test if the given path will evaluate to .. or .
if [ $? -eq 0 ]; then # if they supplied a path of "." or ".."
    echo "Fatal: You cannot give a path that consists only of .. or ."
    exit 1
fi
SUC=0
BASE=$1
fod () {
    if [ -f "$1" ]; then # if the first argument is a file
        echo "  $1 is a file"
        SUC=1
    fi
    if [ -d "$1" ]; then # if the first argument is a directory
        echo "  $1 is a directory"
        fod "$1/$BASE"
        SUC=1
    fi
}
fod "./$BASE"
if [ $SUC -eq 0 ]; then # if the path was not found
    du $1 > /dev/null 2>&1 # disk usage of object at path
    if [ $? -eq 0 ]; then # if du had an error (path exists)
        printf "Fatal: $1 is neither a file nor a directory"
    else # if the path does not exist
        printf "Fatal: $1 does not exist in the current directory or any of its subdirectories"
    fi
    exit 1
fi
